AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Acxhange Library Management System

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.13
    Environment:
      Variables:
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_HOST: !Ref DBHost
        DB_PORT: "3306"
        DB_NAME: !Ref DBName
        SECRET_KEY: !Ref SecretKey
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: "15"

Parameters:
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBHost:
    Type: String
  DBName:
    Type: String
  SecretKey:
    Type: String
    NoEcho: true

Resources:

  AcxLMSFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: acx-lms-api
      CodeUri: .
      Handler: main.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"